# Site settings
title: Cookspring
email: webmaster@thesummitfw.com
description: > # this means to ignore newlines until "baseurl:"
 The Cookspring Shared Kitchen at The Summit in Fort Wayne, Indiana, provides a 2200 square foot commercial kitchen for culinary entrepreneurs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cookspringfw.com" # the base hostname & protocol for your site
images: "/images/"
logo: "/images/logo.png"
encoding: utf-8
highlighter: rouge
# Build settings
markdown: kramdown

sass:
    style: :compressed